### ISSUE TITLE
feature request - falloff control

### ISSUE THREAD

**Issue by jonwong666** [tjm35/asymmetric-tiling-sd-webui#11]
This extension is super useful, I was wondering if a bit more artistic control could be added to give variety ?

adding a padding / falloff value would be amazing

**Comment by tjm35** [comment]
Unfortunately the Stable Diffusion generation this is built on doesn't have any way to be more fine-controlled in its tiling. At each generation step either the image edges are connected to each other, or they aren't; there's no way for the edges to be connected on some parts of the image but not others, for example. Changing *when* the tiling is applied (as currently exposed by the start/end tiling steps) is the only type of more precise control available.
