### ISSUE TITLE
Question: Can I use TileX/ TileY via the API?

### ISSUE THREAD

**Issue by JPhilipp** [tjm35/asymmetric-tiling-sd-webui#3]
Hi! I'm using Unity to connect to the local Automatic1111 API to create dynamic textures on the fly. Is there a way to access the TileX/ TileY settings using the API? Thanks!

**Comment by tjm35** [comment]
Hi; I'm afraid I haven't used the WebUI's API so I'm not an expert, but as far as I can tell it doesn't seem to have any ability to use custom scripts or extensions right now? The WebUI would have to add that support. If it ever does so, I would (perhaps optimistically) expect the asymmetric tiling extension to work with it.

**Comment by tjm35** [comment]
Reading around a little more, there does seem to be a mechanism for the API to call endpoints on extensions, but that doesn't seem like it would be suitable for modifying script generation parameters? It seems like it's intended for adding completely new request types, rather than modifying the parameters for existing ones like txt2img.

**Comment by fbarretto** [comment]
I came across the same "issue" this week for something I've being playing with. I'll try to investigate further and I'll share if I'm able to make it work. Let me know if you've had any advance since this question was posted.

**Comment by stspanho** [comment]
Yes it's possible: 

Active: true
TileX: true
TileY: false
Start: 0
Stop: -1

```
{ ... "alwayson_scripts":{"Asymmetric tiling":{"args":[true,true,false,0,-1]}}}
```

**Comment by neriiacopo** [comment]
Hi everyone!
I am trying to call the the Asymmetric tiling via the API (following @stspanho suggestion) but  am crashing with the following error:
{'detail': 'Cannot have a selectable script in the always on scripts params'}

Recently, anyone that encountered the same issue?
