### ISSUE TITLE
Asymetric tiling not listed among available extensions

### ISSUE THREAD

**Issue by AugmentedRealityCat** [tjm35/asymmetric-tiling-sd-webui#6]
For some reason the Asymmetric Tiling extension is not listed among the extensions available for download and install on the Automatic1111 Webui Extension tab.

Also, if you try to copy-paste the extension's github address on the Install from URL tab, it tells you the extension folder already exists and doesn't do anything.

I used to use the script version but I accidentally deleted it and when I went to reinstall it I discovered there was an extension version - which is much more useful as it can be combined with other scripts now ! Anyways, had I known this was available since November, I would have installed it earlier. And now I am wondering if maybe many other people were not aware of its existence.

Thanks a lot for your Asymmetric Tiling tool - I use it very often and it does its job perfectly. All that was missing, in my uninformed opinion, was an extension version!

**Comment by ClashSAN** [comment]
@AugmentedRealityCat do you have pointers on how to use it properly? I'm not sure using "Euler A" is best for this

**Comment by AugmentedRealityCat** [comment]
It should be quite straightforward to use normally. You just turn it on and select the dimension (X or Y) you want to tile.

Tiling images synthesized with Euler A should not be a problem normally. I just tested it to make sure and it was tiling perfectly on both axis, and even both at the same time.

Can you give me details about what you are trying to achieve ?

**Comment by tjm35** [comment]
> For some reason the Asymmetric Tiling extension is not listed among the extensions available for download and install on the Automatic1111 Webui Extension tab.

That list is maintained by the creators of stable-diffusion-webui as part of their wiki, so they would need to be the ones to add any new extensions to it.

> Also, if you try to copy-paste the extension's github address on the Install from URL tab, it tells you the extension folder already exists and doesn't do anything.

This should work, however; "Install from URL" with the url `https://github.com/tjm35/asymmetric-tiling-sd-webui` and local directory name unspecified is how I install it myself, so I don't know why it wouldn't work for you. Check that you don't already have a `stable-diffusion-webui/extensions/asymmetric-tiling-sd-webui/` folder for some reason, I suppose?

**Comment by tjm35** [comment]
It looks like this extension has now been added to the official list, so I'm going to close this issue. Thanks for raising it!
