### ISSUE TITLE
Add other tiling

### ISSUE THREAD

**Issue by CelestePolo** [tjm35/asymmetric-tiling-sd-webui#8]
Hi,

Do you think it would possible to add asymetric tiling such as:
- left / top
- right / bot
- left / bot
- right / top
?

**Comment by tjm35** [comment]
Not using this extension's methods, I'm afraid, no; we're reliant on wrapping functionality inside pytorch's convolution class, and it's not able to mix axes.

It's possible that a different extension that worked more like [SD Latent Mirroring](https://github.com/dfaker/SD-latent-mirroring) could do this sort of thing, but it's out of scope for this one.
